# Server port is arbitrary
server.port=8082
spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true

# Data Source Setup (example MySQL values). Replace with your production DB credentials.
spring.datasource.url=jdbc:mysql://localhost:3306/critterdb
spring.datasource.username=root
spring.datasource.password=changeme
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Use Hibernate to create/update schema when using local DBs. For production use managed migrations.
spring.jpa.hibernate.ddl-auto=update

# uncomment the below lines to view sql output in console
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
